[package]
name = "hardfloat-test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fuzz_convert"
path = "test/fuzz_convert.rs"

[dependencies]
marlin = { version = "0.1.0", features = [
  "spade",
], path = "/Users/ethan/gh/marlin/marlin/" }
snafu = "0.8.5"
colog = "1.3.0"
rand = "0.9.0"
