name = "hardfloat"
# authors = ["Ethan"]
# license-file = "LICENSE"

# get berkley hardfloat
preprocessing = ["chmod +x ./get_hardfloat.sh", "./get_hardfloat.sh"]

[verilog]
sources = ["src/hardfloat/*.v", "src/hardfloat/*.vi"]
include = ["src/hardfloat/", "src/hardfloat/RISCV"]
