name = "hardfloat"
# authors = ["Ethan"]
# license-file = "LICENSE"

# get berkley hardfloat
preprocessing = ["chmod +x ./get_hardfloat.sh", "./get_hardfloat.sh"]

[verilog]
source = ["src/hardfloat/*.v", "src/hardfloat/*.vi"]
include = ["src/hardfloat/", "src/hardfloat/RISCV"]

[compiler]
git = "https://gitlab.com/ethanuppal/spade.git"
commit = "1640ea90bbba0a57b51122474b7df879912e5b0b"

[simulation]
testbench_dir = "test"
simulator = "icarus"
