name = "hardfloat"
# authors = ["Ethan"]
# license-file = "LICENSE"

# get berkley hardfloat
preprocessing = ["chmod +x ./get_hardfloat.sh", "./get_hardfloat.sh"]

[verilog]
sources = ["verilog/hardfloat/*.v", "verilog/hardfloat/*.vi"]
include = ["verilog/hardfloat/", "verilog/hardfloat/RISCV"]
