name = "hardfloat"
# authors = ["Ethan"]
# license-file = "LICENSE"

# get berkley hardfloat
preprocessing = ["chmod +x ./get_hardfloat.sh", "./get_hardfloat.sh"]

[verilog]
source = ["src/hardfloat/*.v", "src/hardfloat/*.vi"]
include = ["src/hardfloat/", "src/hardfloat/RISCV"]

[compiler]
git = "git@gitlab.com:ethanuppal/spade.git"
commit = "888d2e9b4101335e199fb9aff6a9539958f2783d"

[simulation]
testbench_dir = "test"
simulator = "verilator"
