name: CI

on:
  push:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15]

    steps:
      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v2.7.3

      - name: Install swim
        run: cargo install --git https://gitlab.com/spade-lang/swim.git --rev 9871f3ab4fb64e78947be12622b066136bf42b91

      - name: Run Marlin tests
        run: |
          swim build
          cargo test
